### ISSUE TITLE
Unable to add comments to textarea within modal window

### ISSUE THREAD

**Issue by XigenBen** [openannotation/annotator#488] opened 2015-02-26 13:17 UTC
Hi there, great plugin!

I've run into a minor issue whereby annotations cannot be added from inside a modal popup window. They work on the rest of the page and inside accordions etc.

Screenshot below showing what I'm referring to, the textarea appears to be disabled and cannot be selected:

![screen shot 2015-02-26 at 13 12 47](https://cloud.githubusercontent.com/assets/2797781/6392560/bcac9864-bdb9-11e4-890c-dc45a9d0c40d.png)

I can provide a demo link if required.

Many thanks,
Ben

**Comment by tilgovi** [comment] 2015-02-28 04:12
A working demo that reproduces this would be great. Thank you.

**Comment by XigenBen** [comment] 2015-03-01 17:18
No problem, please find the link as follows: http://proofing.xigen.co.uk/feedback_dev/demo/demo.html

**Comment by XigenMatt** [comment] 2015-03-13 10:59
+1

**Comment by nickstenning** [comment] 2015-03-13 11:16
Thanks folks. We'll look into this when we get a chance.

**Comment by CrazyEraserUK** [comment] 2015-03-31 08:26
I've also noticed this issue, would be great to find a solution. Thanks!

**Comment by XigenMatt** [comment] 2015-03-31 08:39
This is due to the bootstrap modals which are being used having a tabindex="-1" attribute. This means the element (and none of its children) can be focused therefore the textarea can't be selected. Once this attribute is removed from the modal it works as expected. Feel free to close this issue.

**Closed** 2015-03-31 08:41 UTC
