### ISSUE TITLE
Doesn't highlight when using the store plugin (v2)

### ISSUE THREAD

**Issue by chrismichaels84** [openannotation/annotator#528] opened 2015-05-08 03:24 UTC
I'm not sure if this is a bug or user error. I am using the development version 2 release. When I initialize the annotator without the store plugin, all works well.

```javascript
var app = new window.annotator.App();
app.include(window.annotator.ui.main, {element: document.querySelector('#content')});
app.start();
```

However, once I include the store plugin
```javascript
var app = new window.annotator.App();
app.include(window.annotator.ui.main, {element: document.querySelector('#content')});
app.include(window.annotator.storage.http, {
    prefix: '/api'
});
app.start();
```

Then it allows me to create a note and it sends to the api just fine, but the note is not highlighted and does not appear when I hover over it.

When I try to load the saved plugins
```javascript
var app = new window.annotator.App();
app.include(window.annotator.ui.main, {element: document.querySelector('#content')});
app.include(window.annotator.storage.http, {
    prefix: '/api'
});
app.start() 
   .then(function () {
       app.annotations.load();
   });
```

It does retrieve the annotations, but does not highlight them. I'm not sure what the problem is.

It may be an issue with the api. The /api/search request is sending back:
```
{
    "total": 2, 
    "rows": [
        {
            "id":1,
            "startoffset":203,
            "endoffset":212,
            "quote":"Alliance",
            "start":"\/p[1]",
            "end":"\/p[1]",
            "text":"f"
        },
        {
            "id":2,
            "startoffset":21,
            "endoffset":28,
            "quote":"century",
            "start":"\/p[1]",
            "end":"\/p[1]",
            "text":"u"
        }
]}
```

No errors are logged in the console and creating an annotation definitely updates in the database.

Any thoughts?

**Comment by nickstenning** [comment] 2015-05-08 10:43
For general support enquiries [the mailing list](https://lists.okfn.org/mailman/listinfo/annotator-dev) is probably a better bet than the GitHub issue tracker, so if it's okay with you I'm going to close this issue and if you have follow up questions it's best to take them to the mailing list.

That said, the problem is that your search endpoint appears to be returning annotations in a completely different format to the format that they're being created in. Annotations made by `annotator.ui.main` have a `ranges` property. To rework one of your examples above:

```json
{
    "id": 2,
    "quote": "century",
    "text": "...",
    "ranges": [
        {
            "start": "/p[1]",
            "startOffset": 21,
            "end": "/p[1]",
            "endOffset": 28,
        }
    ]
}
```

So I count at least three things you'll need to change:

- ranges property with array of range objects
- `startOffset` not `startoffset`
- slashes in `start` and `end` XPaths don't need escaping

**Closed by nickstenning** 2015-05-08 10:43 UTC

**Comment by cwbuecheler** [comment] 2016-09-26 16:26
Hi guys,

I'm having the same issue (using annotator 1.2.10) and had already diagnosed that the escape slashes in the JSON I'm receiving were the issue. My engineers are looking into removing them but in the interim I'm wondering if it's possible to do any manipulation on the JSON that the store plugin receives before it dumps it to the annotator.

Basically: can I manually get in there are strip the slashes myself somehow so that the existing JSON will work with the annotator?

**Comment by cwbuecheler** [comment] 2016-09-26 19:35
As it turns out, even with the JSON correctly stripped of its slashes, the highlights aren't showing up. I'll see if I can find the problem -- it's probably something in the implementation.
