### ISSUE TITLE
How to show "Create annotation" mockup in viewer itself

### ISSUE THREAD

**Issue by anandi2i** [openannotation/annotator#582] opened 2015-12-10 07:11 UTC
Hi
         I need to do a annotation creation in viewer also , whenever i hover to view an annotation i need an "annotation creation " template there itself.

 which seems like

![ann_combined](https://cloud.githubusercontent.com/assets/6039097/11709140/1e433a48-9f3b-11e5-99cd-0b435ed7a454.png)

Is there a way to do so ?

**Comment by tilgovi** [comment] 2015-12-11 20:19
It should be possible maybe by creating a viewer extension?
http://docs.annotatorjs.org/en/latest/modules/ui.html#viewer-editor-extensions

**Comment by tilgovi** [comment] 2015-12-11 20:19
I'm going to close this issue because it's not a bug report so much as a question.

**Closed as completed by tilgovi** 2015-12-11 20:19 UTC

**Comment by anandi2i** [comment] 2015-12-12 06:51
I dont know...whether it will workout....I really need to do the 'New annotation creation' which should have editor functionality as well.
